/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PollutionWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author RishikRaavi
 */
public class PollutionWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PollutionWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Organization organization; Enterprise enterprise;UserAccount account;EcoSystem business;
    public PollutionWorkAreaJPanel(JPanel userProcessContainer,Organization organization, Enterprise enterprise,UserAccount account,EcoSystem business) {
        initComponents();
        this.organization=organization;
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.account=account;
        this.business=business;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PolEnt = new javax.swing.JButton();
        PolUser = new javax.swing.JButton();
        PolOrg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        PolEnt.setBackground(new java.awt.Color(0, 153, 204));
        PolEnt.setText("Manage Pollution  Employee");
        PolEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolEntActionPerformed(evt);
            }
        });

        PolUser.setBackground(new java.awt.Color(0, 153, 204));
        PolUser.setText("Manage Pollution User Accounts");
        PolUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolUserActionPerformed(evt);
            }
        });

        PolOrg.setBackground(new java.awt.Color(0, 153, 204));
        PolOrg.setText("Manage Pollution  Organization");
        PolOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PolOrgActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Pollution Work Area");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/PollutionWorkArea/pollutioncontrols.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PolEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PolOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PolUser, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PolOrg, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(PolEnt, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PolUser, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addGap(0, 11, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PolUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolUserActionPerformed
        // TODO add your handling code here:
        ManagePollutionUserAccountsJPanel mwrp = new ManagePollutionUserAccountsJPanel(userProcessContainer,account,organization,enterprise,business);
        userProcessContainer.add("Manage User",mwrp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_PolUserActionPerformed

    private void PolOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolOrgActionPerformed
        // TODO add your handling code here:
        ManagePollutionOrganizationJPanel mwrp = new ManagePollutionOrganizationJPanel(userProcessContainer,account,organization,enterprise);
        userProcessContainer.add("Manage Organization",mwrp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_PolOrgActionPerformed

    private void PolEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PolEntActionPerformed
        // TODO add your handling code here:
        ManagePollutionEmployeeJPanel mwrp = new ManagePollutionEmployeeJPanel(userProcessContainer,account,organization,enterprise);
        userProcessContainer.add("Manage Employee",mwrp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_PolEntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PolEnt;
    private javax.swing.JButton PolOrg;
    private javax.swing.JButton PolUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
