/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.WasteWorkArea;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.PollutionControlAdmin;
import static Business.Organization.Organization.Type.RecycleAdmin;
import static Business.Organization.Organization.Type.RecylceWorker;
import static Business.Organization.Organization.Type.WasteControlAdmin;
import static Business.Organization.Organization.Type.WasteTracker;
import Business.Organization.RecycleAdminOrganization;
import Business.Organization.RecycleWorkerOrganization;
import Business.Organization.WasteControlAdminOrganization;
import Business.Organization.WasteTrackerOrganization;
import Business.Role.RecycleControlAdmin;
import Business.Role.RecycleWorker;
import Business.Role.WasteControlAdmin;
import Business.Role.WasteTracker;


import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RishikRaavi
 */
public class ManageWasteOrganization extends javax.swing.JPanel {

    /**
     * Creates new form ManageWasteOrganization
     */
    JPanel userProcessContainer; UserAccount account; Organization organization; Enterprise enterprise;
    public ManageWasteOrganization(JPanel userProcessContainer, UserAccount account, Organization organization, Enterprise enterprise) {
        initComponents();
        this.organization=organization;
        this.account=account;
        this.enterprise=enterprise;
        this.userProcessContainer=userProcessContainer;
         populateCombo();
        populateTable();
    }

 public void populateCombo(){
  organizationComboBox.removeAllItems();

        for (Organization.Type type : Organization.Type.values()) {
            if (type.getValue().equals(Organization.Type.WasteTracker.getValue()) || type.getValue().equals(Organization.Type.WasteControlAdmin.getValue()) || type.getValue().equals(Organization.Type.RecycleAdmin.getValue()) || type.getValue().equals(Organization.Type.RecylceWorker.getValue())) {
                organizationComboBox.addItem(type);
            }
        }
 
 }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addJButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        organizationJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        organizationComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        addJButton.setBackground(new java.awt.Color(0, 204, 51));
        addJButton.setText("Add Organization");
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(0, 204, 51));
        backButton.setText(">>Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        organizationJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationJTable);

        jLabel1.setText("Organization Type:");

        organizationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        organizationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                organizationComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText("Manage Organization");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/WasteWorkArea/icon2-1024x1024.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jLabel3)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(organizationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addJButton)))
                    .addContainerGap(606, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 285, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(56, 56, 56)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(organizationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(24, 24, 24)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(backButton)
                        .addComponent(addJButton))
                    .addContainerGap(425, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed
        // TODO add your handling code here:

        Organization.Type type = (Organization.Type) organizationComboBox.getSelectedItem();

        for (Organization organ : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if(organ instanceof WasteControlAdminOrganization && type == WasteControlAdmin ){
                JOptionPane.showMessageDialog(null,"WasteControlAdminOrganization already exists");
                return;
            }
            else if( organ instanceof WasteTrackerOrganization && type == WasteTracker){
                JOptionPane.showMessageDialog(null,"WasteTrackerOrganization already exists");
                return;

            }
            else if( organ instanceof RecycleAdminOrganization && type == RecycleAdmin){
                JOptionPane.showMessageDialog(null,"RecycleAdminOrganization already exists");
                return;

            }
            else if( organ instanceof RecycleWorkerOrganization && type == RecylceWorker){
                JOptionPane.showMessageDialog(null,"RecycleWorkerOrganization already exists");
                return;

            }
        }

        Organization org = enterprise.getOrganizationDirectory().createOrganization(type);
        if ((type.getValue().equals(Organization.Type.WasteControlAdmin.getValue()))) {
            org.getSupportedRole().add(new WasteControlAdmin());

        } else if ((type.getValue().equals(Organization.Type.WasteTracker.getValue()))) {
            org.getSupportedRole().add(new WasteTracker());

        }
        else if ((type.getValue().equals(Organization.Type.RecycleAdmin.getValue()))) {
            org.getSupportedRole().add(new RecycleControlAdmin());

        }
        else if ((type.getValue().equals(Organization.Type.RecylceWorker.getValue()))) {
            org.getSupportedRole().add(new RecycleWorker());

        }
        populateTable();
    }//GEN-LAST:event_addJButtonActionPerformed
public void populateTable(){
    DefaultTableModel model = (DefaultTableModel) organizationJTable.getModel();

        model.setRowCount(0);

        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();

            model.addRow(row);
        }



}
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void organizationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_organizationComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_organizationComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addJButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationComboBox;
    private javax.swing.JTable organizationJTable;
    // End of variables declaration//GEN-END:variables
}
