/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Waste;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.RecycleAdminOrganization;
import Business.Organization.WasteControlAdminOrganization;
import Business.Role.RecycleControlAdmin;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WasteSensor.WasteSensor;
import Business.WorkQueue.WasteWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.Timestamp;
import java.text.MessageFormat;
import java.util.Date;
import java.util.Locale;
import java.util.TreeMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFFont;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author RishikRaavi
 */
public class WasteControlAdminRequest extends javax.swing.JPanel {

    /**
     * Creates new form WasteControlAdminRequest
     */
    java.util.Date date = new java.util.Date();
    Date timeStamp = new Timestamp(date.getTime());
    JPanel userProcessContainer;
    UserAccount account;
    UserAccount userAccount;
    WasteControlAdminOrganization wasteControlAdminOrganization;
    Enterprise enterprise;

    public WasteControlAdminRequest(JPanel userProcessContainer, UserAccount userAccount, WasteControlAdminOrganization wasteControlAdminOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;

        this.enterprise = enterprise;
        this.wasteControlAdminOrganization = wasteControlAdminOrganization;
        this.userAccount = userAccount;
        populateWorkRequestTable();
        rbDisable();
    }

    public void rbDisable() {
        rbOne.setEnabled(false);
        rbTwo.setEnabled(false);
        rbThree.setEnabled(false);
        rbFour.setEnabled(false);
        rbFive.setEnabled(false);
        rbSix.setEnabled(false);
        rbSeven.setEnabled(false);

        rbOne.setVisible(false);
        rbTwo.setVisible(false);
        rbThree.setVisible(false);
        rbFour.setVisible(false);
        rbFive.setVisible(false);
        rbSix.setVisible(false);
        rbSeven.setVisible(false);

        rbOne.setSelected(false);
        rbThree.setSelected(false);
        rbTwo.setSelected(false);
        rbFive.setSelected(false);
        rbFour.setSelected(false);
        rbSix.setSelected(false);
        rbSeven.setSelected(false);

        img1.setVisible(false);
        img2.setVisible(false);
        img3.setVisible(false);
        img4.setVisible(false);
        img5.setVisible(false);
        img6.setVisible(false);
        img7.setVisible(false);

        lblOne.setVisible(false);
        lblTwo.setVisible(false);
        lblThree.setVisible(false);
        lblFour.setVisible(false);
        lblFive.setVisible(false);
        lblSix.setVisible(false);
        lblSeven.setVisible(false);

        statusJtext.setVisible(false);
        jLabel6.setVisible(false);

    }

    public void rbEnable() {

        rbOne.setVisible(true);
        rbTwo.setVisible(true);
        rbThree.setVisible(true);
        rbFour.setVisible(true);
        rbFive.setVisible(true);
        rbSix.setVisible(true);
        rbSeven.setVisible(true);

        lblOne.setVisible(true);
        lblTwo.setVisible(true);
        lblThree.setVisible(true);
        lblFour.setVisible(true);
        lblFive.setVisible(true);
        lblSix.setVisible(true);
        lblSeven.setVisible(true);

        statusJtext.setVisible(true);
        jLabel6.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtZipCode = new javax.swing.JTextField();
        btnExport = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        wrkReqTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSentDate = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        txtAssignedRA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSubmitResult = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        rbFour = new javax.swing.JRadioButton();
        lblOne = new javax.swing.JLabel();
        lblTwo = new javax.swing.JLabel();
        lblThree = new javax.swing.JLabel();
        lblFour = new javax.swing.JLabel();
        rbSeven = new javax.swing.JRadioButton();
        lblFive = new javax.swing.JLabel();
        lblSix = new javax.swing.JLabel();
        lblSeven = new javax.swing.JLabel();
        rbSix = new javax.swing.JRadioButton();
        rbOne = new javax.swing.JRadioButton();
        rbTwo = new javax.swing.JRadioButton();
        rbThree = new javax.swing.JRadioButton();
        rbFive = new javax.swing.JRadioButton();
        img1 = new javax.swing.JLabel();
        img2 = new javax.swing.JLabel();
        img3 = new javax.swing.JLabel();
        img4 = new javax.swing.JLabel();
        img5 = new javax.swing.JLabel();
        img6 = new javax.swing.JLabel();
        img7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        statusJtext = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Zip Code");

        txtZipCode.setEditable(false);

        btnExport.setBackground(new java.awt.Color(0, 204, 51));
        btnExport.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnExport.setText("Export To Excel");
        btnExport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        jButton1.setText("Assign Request To Me");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        wrkReqTable.setBackground(new java.awt.Color(153, 255, 255));
        wrkReqTable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        wrkReqTable.setForeground(new java.awt.Color(51, 0, 255));
        wrkReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Location", "Sender", "Receiver", "Status", "Emergency Level", "Total Waste (Tons)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(wrkReqTable);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Sent Date");
        jLabel4.setToolTipText("");

        txtSentDate.setEditable(false);
        txtSentDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSentDateActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(0, 204, 51));
        btnBack.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Assigned Recycle Admin");
        jLabel5.setToolTipText("");

        txtResult.setToolTipText("");

        txtAssignedRA.setEditable(false);
        txtAssignedRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAssignedRAActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Action To Be Taken");
        jLabel2.setToolTipText("");

        btnSubmitResult.setBackground(new java.awt.Color(0, 204, 51));
        btnSubmitResult.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnSubmitResult.setText("Submit Result");
        btnSubmitResult.setEnabled(false);
        btnSubmitResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitResultActionPerformed(evt);
            }
        });

        btnPrint.setBackground(new java.awt.Color(0, 204, 51));
        btnPrint.setFont(new java.awt.Font("Times New Roman", 1, 13)); // NOI18N
        btnPrint.setText("Print Data");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 51));
        jLabel6.setText("Manage Work Admin Requests");

        jButton2.setBackground(new java.awt.Color(0, 204, 51));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Pie chart For Waste");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        rbFour.setText("-----------");

        lblOne.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblOne.setText("Sent");
        lblOne.setToolTipText("");

        lblTwo.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblTwo.setText("Pending");

        lblThree.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblThree.setText("Sent to RAdmin");

        lblFour.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblFour.setText("Pending for Recycling");

        rbSeven.setToolTipText("");
        rbSeven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSevenActionPerformed(evt);
            }
        });

        lblFive.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblFive.setText("Sent to RWorker");

        lblSix.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblSix.setText("Assigned to Worker");

        lblSeven.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        lblSeven.setText("Completed");

        rbSix.setText("-------------");
        rbSix.setToolTipText("");
        rbSix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSixActionPerformed(evt);
            }
        });

        rbOne.setText("-----------");

        rbTwo.setText("-----------");

        rbThree.setText("-----------");

        rbFive.setText("-----------");
        rbFive.setToolTipText("");

        img1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Waste/tick_button.png"))); // NOI18N

        img2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Waste/tick_button.png"))); // NOI18N

        img3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Waste/tick_button.png"))); // NOI18N

        img4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Waste/tick_button.png"))); // NOI18N

        img5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Waste/tick_button.png"))); // NOI18N

        img6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Waste/tick_button.png"))); // NOI18N

        img7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userinterface/Waste/tick_button.png"))); // NOI18N

        jLabel1.setText("Status");

        statusJtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusJtextActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 204, 51));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setText("Check Status");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(422, 422, 422)
                                    .addComponent(btnSubmitResult))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(81, 81, 81)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtAssignedRA, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(87, 87, 87)
                                                    .addComponent(txtSentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblOne)
                                                    .addComponent(rbOne)
                                                    .addComponent(img1)))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGap(40, 40, 40)
                                                    .addComponent(jLabel1)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(statusJtext, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rbTwo)
                                                        .addComponent(lblTwo)
                                                        .addComponent(img2))
                                                    .addGap(5, 5, 5)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rbThree)
                                                        .addComponent(img3)
                                                        .addComponent(lblThree))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(lblFour, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(lblFive))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(rbFour)
                                                                .addComponent(img4))
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(img5)
                                                                .addComponent(rbFive))))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rbSix)
                                                        .addComponent(lblSix)
                                                        .addComponent(img6))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(img7)
                                                        .addComponent(lblSeven)
                                                        .addComponent(rbSeven))))))
                                    .addGap(50, 50, 50)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(3, 3, 3)
                                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExport, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton2)
                .addGap(35, 35, 35)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(57, 57, 57))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(jLabel1)
                            .addComponent(statusJtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAssignedRA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel3)
                        .addComponent(txtZipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtSentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSubmitResult))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblTwo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(lblThree)))
                                .addGap(6, 6, 6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblOne)
                                        .addGap(9, 9, 9))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFour)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblSix, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblFive)
                                                .addComponent(lblSeven)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rbSeven)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbOne)
                                .addComponent(rbTwo)
                                .addComponent(rbThree)
                                .addComponent(rbFour)
                                .addComponent(rbSix)
                                .addComponent(rbFive)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(img1)
                            .addComponent(img3)
                            .addComponent(img4)
                            .addComponent(img5)
                            .addComponent(img6)
                            .addComponent(img7)
                            .addComponent(img2))))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(jButton2)
                    .addComponent(btnExport))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportActionPerformed
        // TODO add your handling code here:
        HSSFWorkbook fWorkbook = new HSSFWorkbook();
        HSSFSheet fSheet = fWorkbook.createSheet("new Sheet");
        TreeMap<String, Object[]> data = new TreeMap<>();

        HSSFFont sheetTitleFont = fWorkbook.createFont();
        File file = new File(new File("").getAbsolutePath() + "/Waste.xls");
        HSSFCellStyle cellStyle = fWorkbook.createCellStyle();

        sheetTitleFont.setBoldweight(HSSFFont.BOLDWEIGHT_BOLD);
        //sheetTitleFont.setColor();
        TableModel model = wrkReqTable.getModel();
        TableColumnModel tcm = wrkReqTable.getColumnModel();
        HSSFRow fRow1 = fSheet.createRow((short) 0);

        for (int i = 0; i < model.getRowCount(); i++) {

            HSSFRow fRow = fSheet.createRow((short) i);
            for (int j = 0; j < model.getColumnCount(); j++) {
                HSSFCell cell = fRow.createCell((short) j);
                cell.setCellValue(tcm.getColumn(j).getHeaderValue().toString());
                cell.setCellValue(model.getValueAt(i, j).toString());
                cell.setCellStyle(cellStyle);

            }

        }
        try {
            FileOutputStream fileOutputStream;
            fileOutputStream = new FileOutputStream(file);
            BufferedOutputStream bos = new BufferedOutputStream(fileOutputStream);
            fWorkbook.write(bos);
            bos.close();
            fileOutputStream.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "vvxcvxcv");
        }
    }//GEN-LAST:event_btnExportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel) wrkReqTable.getModel();
        int selectedRow = wrkReqTable.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to assign the request",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            String statusFlag = (String) model.getValueAt(selectedRow, 3);
            if (statusFlag.equals("Completed") || statusFlag.equals("Sent to Recycle Admin")) {
                JOptionPane.showMessageDialog(null, "The work request cant be assigned as it is completed or sent to Recycle Admin");
                return;
            }

            WasteWorkRequest request = (WasteWorkRequest) wrkReqTable.getValueAt(selectedRow, 0);
            request.setReceiver(userAccount);
            request.setStatus("Pending");
            populateWorkRequestTable();
            btnSubmitResult.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Request assigned to you successfully",
                    "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void populateWorkRequestTable() {
        DefaultTableModel model = (DefaultTableModel) wrkReqTable.getModel();
        model.setRowCount(0);

        for (WorkRequest request : wasteControlAdminOrganization.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getSender().getEmployee().getName();
            row[2] = request.getReceiver() == null ? "To be Assigned" : request.getReceiver().getEmployee().getName();
            row[3] = request.getStatus();
            row[4] = ((WasteWorkRequest) request).getEmerLevel();
            row[5] = ((WasteWorkRequest) request).getTotalWaste();
            wrkReqTable.getColumnModel().getColumn(3).setMinWidth(0);
            wrkReqTable.getColumnModel().getColumn(3).setMaxWidth(0);
            wrkReqTable.getColumnModel().getColumn(3).setWidth(0);

            model.addRow(row);
        }

    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitResultActionPerformed

        DefaultTableModel model = (DefaultTableModel) wrkReqTable.getModel();

        int selectedRow = wrkReqTable.getSelectedRow();

        if (selectedRow >= 0) {

            String assignedReceiver = (String) model.getValueAt(selectedRow, 2);

            String statusFlag = (String) model.getValueAt(selectedRow, 3);

            if (assignedReceiver == null) {
                JOptionPane.showMessageDialog(null, "Please assign a receiver",
                        "Warning", JOptionPane.WARNING_MESSAGE);
                return;

            } else if (statusFlag.equals("Sent")) {
                JOptionPane.showMessageDialog(null, "The work request cant be completed as it is not assigned yet");
                return;
            } else if (statusFlag.equals("Sent to Recycle Admin") || statusFlag.equals("Completed")) {
                JOptionPane.showMessageDialog(null, "The work request cant be pushed as it is sent to Recycle Admin/Completed");
                return;
            } else if (statusFlag.equals("Sent to Recycle Worker")) {
                JOptionPane.showMessageDialog(null, "The work request cant be pushed as it is sent to Recycle Worker");
                return;
            } else if (txtResult.getText() == null || txtResult.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Action to be taken cannot be blank");
                return;
            } else {

                WasteWorkRequest request = (WasteWorkRequest) (WorkRequest) wrkReqTable.getValueAt(selectedRow, 0);

                txtZipCode.setText("0" + String.valueOf(((WasteWorkRequest) request).getZipCode()));
                request.setResult(txtResult.getText());
                request.setStatus("Sent");
                request.setSentDate(timeStamp);

                populateWorkRequestTable();

                //push data to Recycle Admin
                WasteWorkRequest wt = (WasteWorkRequest) model.getValueAt(selectedRow, 0);

                RecycleControlAdmin r;
                String message = wt.getMessage();
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                        Role role = ua.getRole();
                        if (role instanceof RecycleControlAdmin) {
                            account = ua;
                        }
                    }
                }

                txtSentDate.setText(timeStamp.toString());
                txtAssignedRA.setText(account.toString());

                WasteWorkRequest request1 = new WasteWorkRequest();
                request1.setMessage(message);
                request1.setSender(userAccount);
                request1.setStatus("Sent to Recycle Admin");
                request1.setReceiver(account);
                request1.setEmerLevel(wt.getEmerLevel());
                request1.setTotalWaste(wt.getTotalWaste());
                request1.setZipCode(wt.getZipCode());
                request1.setResult(txtResult.getText());
                request1.setSentDate(timeStamp);

                Organization org = null;
                for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof RecycleAdminOrganization) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    org.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);

                }

                // pushDataToRecycleAdmin();
                JOptionPane.showMessageDialog(null, "Request completed successfully",
                        "Information", JOptionPane.INFORMATION_MESSAGE);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to submit the request",
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSubmitResultActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed

        MessageFormat header = new MessageFormat("Report Print");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");

        try {
            wrkReqTable.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s %n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultPieDataset piedataset = new DefaultPieDataset();
        int rowcount = wrkReqTable.getRowCount();

        for (int i = 0; i <= rowcount - 1; i++) {
            WasteWorkRequest inventory = (WasteWorkRequest) wrkReqTable.getValueAt(i, 0);
            int j = inventory.getTotalWaste();
            piedataset.setValue(inventory.toString(), j);

        }
        JFreeChart freechart = ChartFactory.createPieChart("Pie Chart for Inventory", piedataset, true, true, Locale.ENGLISH);
        PiePlot plot = (PiePlot) freechart.getPlot();
        //plot.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("Pie Chart", freechart);
        frame.setVisible(true);
        frame.setSize(500, 500);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAssignedRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAssignedRAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAssignedRAActionPerformed

    private void rbSevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSevenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSevenActionPerformed

    private void statusJtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusJtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusJtextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        rbDisable();
        int selectedRow = wrkReqTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to check the status.");
            return;
        } else {
            String message = null;
            WasteWorkRequest hosprequest = (WasteWorkRequest) wrkReqTable.getValueAt(selectedRow, 0);

            message = hosprequest.getStatus();

            if (message != null) {
                if (message.equals("Sent")) {
                    rbEnable();
                    rbOne.setSelected(true);
                    img1.setVisible(true);
                    statusJtext.setText(message);
                } else if (message.equals("Pending")) {
                    rbEnable();
                    rbTwo.setSelected(true);
                    img2.setVisible(true);
                    statusJtext.setText(message);
                } else if (message.equals("Sent to Recycle Admin")) {
                    rbEnable();
                    rbThree.setSelected(true);
                    img3.setVisible(true);
                    statusJtext.setText(message);
                } else if (message.equals("Pending For Recycling")) {
                    rbEnable();
                    rbFour.setSelected(true);
                    img4.setVisible(true);
                    statusJtext.setText(message);
                } else if (message.equals("Sent to Recycle Worker")) {
                    rbEnable();
                    rbFive.setSelected(true);
                    img5.setVisible(true);
                    statusJtext.setText(message);
                } else if (message.equals("Assigned")) {
                    rbEnable();
                    rbSix.setSelected(true);
                    img6.setVisible(true);
                    statusJtext.setText(message);
                } else {
                    rbEnable();
                    rbSeven.setSelected(true);
                    img7.setVisible(true);
                    statusJtext.setText(message);
                }
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtSentDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSentDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSentDateActionPerformed

    private void rbSixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSixActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSixActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSubmitResult;
    private javax.swing.JLabel img1;
    private javax.swing.JLabel img2;
    private javax.swing.JLabel img3;
    private javax.swing.JLabel img4;
    private javax.swing.JLabel img5;
    private javax.swing.JLabel img6;
    private javax.swing.JLabel img7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFive;
    private javax.swing.JLabel lblFour;
    private javax.swing.JLabel lblOne;
    private javax.swing.JLabel lblSeven;
    private javax.swing.JLabel lblSix;
    private javax.swing.JLabel lblThree;
    private javax.swing.JLabel lblTwo;
    private javax.swing.JRadioButton rbFive;
    private javax.swing.JRadioButton rbFour;
    private javax.swing.JRadioButton rbOne;
    private javax.swing.JRadioButton rbSeven;
    private javax.swing.JRadioButton rbSix;
    private javax.swing.JRadioButton rbThree;
    private javax.swing.JRadioButton rbTwo;
    private javax.swing.JTextField statusJtext;
    private javax.swing.JTextField txtAssignedRA;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtSentDate;
    private javax.swing.JTextField txtZipCode;
    private javax.swing.JTable wrkReqTable;
    // End of variables declaration//GEN-END:variables
}
