/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Parking;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import static Business.Organization.Organization.Type.ParkingControlAdmin;
import Business.Organization.ParkingControlAdminOrganization;
import Business.Organization.ParkingOfficerOrganization;
import Business.Person.Person;
import Business.Role.ParkingControlAdmin;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ParkingWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RishikRaavi
 */
public class ManageWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form ManageWorkRequest
     */JPanel userProcessContainer;  UserAccount userAccount;
    UserAccount account; ParkingOfficerOrganization parkingOfficerOrganization; Enterprise enterprise;
    public ManageWorkRequest(JPanel userProcessContainer, UserAccount account, ParkingOfficerOrganization parkingOfficerOrganization, Enterprise enterprise) {
        initComponents();
        this.enterprise=enterprise;
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.parkingOfficerOrganization=parkingOfficerOrganization;
        populateAmountTable();
       // populateWorkRequestTable();
    }
public void populateAmountTable() {
        DefaultTableModel model = (DefaultTableModel) personTable1.getModel();
        model.setRowCount(0);
        if (enterprise.getPersonList().getPersonList() != null) {
            for (Person p : enterprise.getPersonList().getPersonList()) {

                Object row[] = new Object[7];
                row[0] = p;
                row[1] = p.getPersonFirstName() + p.getPersonLastName();
                row[2] = p.getVehcileNumber();
                row[3] = p.getArea();
                row[4] = p.getTotalPrice();
                row[5] =  p.getBillNo();
                row[6] =  "Ticket Generated";

                ((DefaultTableModel) personTable1.getModel()).addRow(row);
            }
        }

    }
public void populateWorkRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tblManageRequest.getModel();
        model.setRowCount(0);
        if (userAccount.getWorkQueue().getWorkRequestList() != null) {
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[6];
            row[0] = request;
            row[1] = request.getReceiver();
            row[2] = request.getStatus();
            String result = ((ParkingWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
            String emLevel = ((ParkingWorkRequest) request).getAddress();
            row[4] = emLevel;
            float carbonO2 = ((ParkingWorkRequest) request).getTotalPrice();
            row[5] = carbonO2;

            model.addRow(row);
        }

    }}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        personTable1 = new javax.swing.JTable();
        btnCreateWorkRequest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageRequest = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        personTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Person Id", "Name", "Vehcile Number", "Area", "Total Price", "Bill No", "Ticket Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(personTable1);

        btnCreateWorkRequest.setText("Create Work Request");
        btnCreateWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateWorkRequestActionPerformed(evt);
            }
        });

        tblManageRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Receiver", "Message", "Status", "Result"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageRequest);

        jButton1.setText("<<Back");

        jLabel1.setText("Manage Request");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnCreateWorkRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCreateWorkRequest)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateWorkRequestActionPerformed

        int selectedRow = personTable1.getSelectedRow();

        if (selectedRow >= 0) {
            DefaultTableModel model = (DefaultTableModel) personTable1.getModel();
            Person p = (Person) model.getValueAt(selectedRow, 0);
            ParkingControlAdmin pa;
            String message = p.getArea();
            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                for (UserAccount ua : org.getUserAccountDirectory().getUserAccountList()) {
                    Role role = ua.getRole();
                    if (role instanceof ParkingControlAdmin) {
                        account = ua;
                    }

                }

            }
            ParkingWorkRequest pwr = new ParkingWorkRequest();
            pwr.setMessage(message);
            pwr.setSender(userAccount);
            pwr.setStatus("Sent");
            pwr.setReceiver(account);
            pwr.setAddress(p.getAddress());
            pwr.setTotalPrice(p.getTotalPrice());
            pwr.setZipCode(p.getZipCode());

            Organization org = null;
            for (Organization org1 : enterprise.getOrganizationDirectory().getOrganizationList()) {
                if (org1 instanceof ParkingControlAdminOrganization) {
                    org = org1;
                    break;
                }
            }
            if (org != null) {
                org.getWorkQueue().getWorkRequestList().add(pwr);
                userAccount.getWorkQueue().getWorkRequestList().add(pwr);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Row");
            return;

        }
        populateWorkRequestTable();
        JOptionPane.showMessageDialog(null, "Work Request was added successfully");
        System.out.println(userAccount.getWorkQueue().getWorkRequestList().size());
    }//GEN-LAST:event_btnCreateWorkRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateWorkRequest;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable personTable1;
    private javax.swing.JTable tblManageRequest;
    // End of variables declaration//GEN-END:variables
}
