/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Parking;

import Business.Enterprise.Enterprise;
import Business.Organization.ParkingOfficerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import userinterface.ParkingWorkArea.ManageParkingUserAccountsJPanel;

/**
 *
 * @author RishikRaavi
 */
public class ParkingOfficerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ParkingOfficerWorkAreaJPanel
     */
    JPanel userProcessContainer; UserAccount account; ParkingOfficerOrganization parkingOfficerOrganization; Enterprise enterprise;
    public ParkingOfficerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ParkingOfficerOrganization parkingOfficerOrganization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.parkingOfficerOrganization=parkingOfficerOrganization;
        this.enterprise=enterprise;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managePerson = new javax.swing.JButton();
        manageParking = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        managePerson.setText("Manage Person");
        managePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managePersonActionPerformed(evt);
            }
        });

        manageParking.setText("Manage Parking Request");
        manageParking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageParkingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(managePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(manageParking)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(manageParking, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void managePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managePersonActionPerformed
        // TODO add your handling code here:
        ManagePerson mwrp = new ManagePerson(userProcessContainer,account,parkingOfficerOrganization,enterprise);
        userProcessContainer.add("Manage User",mwrp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_managePersonActionPerformed

    private void manageParkingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageParkingActionPerformed
        // TODO add your handling code here:
        ManageParkingRequest mwrp = new ManageParkingRequest(userProcessContainer,account,parkingOfficerOrganization,enterprise);
        userProcessContainer.add("Manage User",mwrp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageParkingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton manageParking;
    private javax.swing.JButton managePerson;
    // End of variables declaration//GEN-END:variables
}
